//controls
const KEY_UP = 38;
const KEY_LEFT = 39;
const KEY_DOWN = 40;
const KEY_RIGHT = 37;
const KEY_SPACE = 32;

//speeds
const ANGLE_ROTATION_SPEED = 3;
const SPEED_LIMIT = 4;
const BACK_THRUSTER_LIMIT = 4;

// particles
const LIMIT_OF_PARTICLES_FRONT_THRUST = 3;
const LIFETIME_OF_PARTICLES_FRONT_THRUST = 10;
const FRONT_THRUST_SHOT_SPEED = 10;
const COLOR_OF_PARTICLES_FRONT_THRUST = "yellow";

const LIMIT_OF_PARTICLES_BACK_THRUST = 2;
const LIFETIME_OF_PARTICLES_BACK_THRUST = 10;
const BACK_THRUST_SHOT_SPEED = 15;
const COLOR_OF_PARTICLES_BACK_THRUST = "red";

const BASIC_SHOT_LIFETIME = 300;
const BASIC_SHOT_SPEED = 14;
const BASIC_SHOT_COLOR = "white";
const BASIC_SHOT_WIDTH = 14;
const BASIC_SHOT_TIME_LIMIT = 10;

//asteroids
const LIMIT_OF_ASTEROID_MAX_VECTORS = 10;
const LIMIT_OF_MIN_ASTEROID_VECTORS = 5;
const LIMIT_OF_MAX_ASTEROID_LENGTH = 50;
const LIMIT_OF_MIN_ASTEROID_LENGTH = 40;
const LIMIT_OF_MIN_ASTEROID_SPEED = 0.2;
const LIMIT_OF_MAX_ASTEROID_SPEED = 1;
const LIMIT_OF_MAX_ASTEROIDS = 5;
